query {
  products(category: "2") {
    categoryId
    items {
      itemId
      name
      nameComplete
      sellers {
        commertialOffer {
          Price
          ListPrice
          spotPrice
        }
      }
      images {
        imageUrl
      }
    }
  }
}